// <auto-generated />
using System;
using ContentForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentForge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831122019_AddContentEntryQueryIndexes")]
    partial class AddContentEntryQueryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DraftDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PublishedSnapshotJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ScheduledPublishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledUnpublishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("ScheduledPublishAt");

                    b.HasIndex("ScheduledUnpublishAt");

                    b.HasIndex("Slug");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("ContentTypeId", "Slug")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ContentTypeId", "IsDeleted", "PublishedAt");

                    b.HasIndex("ContentTypeId", "IsDeleted", "UpdatedAt");

                    b.ToTable("ContentEntries", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentEntryRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SourceEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceEntryId");

                    b.HasIndex("TargetEntryId");

                    b.HasIndex("SourceEntryId", "FieldName");

                    b.HasIndex("SourceEntryId", "TargetEntryId", "FieldName")
                        .IsUnique();

                    b.ToTable("ContentEntryRelations", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentPreviewTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ContentEntryId", "RevokedAt", "ExpiresAt");

                    b.ToTable("ContentPreviewTokens", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ContentTypes", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentTypeFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId", "Name")
                        .IsUnique();

                    b.HasIndex("ContentTypeId", "SortOrder");

                    b.ToTable("ContentTypeFields", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ContentEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentEntryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ContentEntryId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContentVersions", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.MediaAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000001"),
                            Name = "content.read"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000002"),
                            Name = "content.create"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000003"),
                            Name = "content.update"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000004"),
                            Name = "content.delete"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000005"),
                            Name = "content.publish"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000006"),
                            Name = "content.archive"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000007"),
                            Name = "content.restore"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000008"),
                            Name = "content.review"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000009"),
                            Name = "content.version.read"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000010"),
                            Name = "content.version.restore"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000011"),
                            Name = "contentType.read"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000012"),
                            Name = "contentType.create"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000013"),
                            Name = "contentType.update"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000014"),
                            Name = "contentType.delete"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000015"),
                            Name = "media.read"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000016"),
                            Name = "media.upload"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000017"),
                            Name = "media.update"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000018"),
                            Name = "media.delete"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000019"),
                            Name = "user.read"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000020"),
                            Name = "user.create"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000021"),
                            Name = "user.update"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000022"),
                            Name = "user.disable"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000023"),
                            Name = "audit.read"
                        });
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Name = "Editor"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Name = "Author"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000014")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000016")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000017")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000018")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000019")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000020")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000021")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000022")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000023")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000016")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000017")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000018")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000016")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PermissionId = new Guid("22222222-2222-2222-2222-000000000009")
                        });
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ScheduledJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContentEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("LockedUntil");

                    b.HasIndex("Status", "ScheduledAt");

                    b.HasIndex("ContentEntryId", "JobType", "Status");

                    b.ToTable("ScheduledJobs", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentEntryEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("Entries")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentEntryRelationEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentEntryEntity", "SourceEntry")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentEntryEntity", "TargetEntry")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEntry");

                    b.Navigation("TargetEntry");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentTypeFieldEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentVersionEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentEntryEntity", "ContentEntry")
                        .WithMany("Versions")
                        .HasForeignKey("ContentEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentEntry");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentEntryEntity", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("OutgoingRelations");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentForgeUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.ContentTypeEntity", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ContentForge.Infrastructure.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
